Allow publishing contracts as NPM packages
ton-org/blueprint pull request #41
Opened 2023-05-25 17:00 UTC by Gusarich

Should be merged with https://github.com/ton-community/create-ton/pull/5

2023-05-25 17:16 UTC, Gusarich commented
I just understood that this version won't work properly with regular FunC/Tact contracts. I tested it with my github.com/Gusarich/fake-nft contract and it worked well — because the compiled contract's code was hardcoded into wrapper.

I'll need to do update this PR in order to handle regular FunC and Tact contracts too.

2024-09-27 16:27 UTC, efren171 approved these changes

2024-10-03 04:49 UTC, Fart10 requested changes
..

2024-10-26 12:15 UTC, Fart10 reviewed
.

2025-05-16 13:00 UTC, Alejandbel commented
Reintroduced via https://github.com/ton-org/blueprint/issues/192. Closing as reworked

2025-05-16 13:00 UTC, closed without merging